project:
  type: website
  output-dir: docs

jupyter: quarto-env/bin/python

website:
  title: "Jonny Comes"
  navbar:
    background: white
    foreground: dark
    left:
      - posts.qmd
      - projects.qmd
      - text: "Research"
        menu:
          - publications.qmd
          - students.qmd
      - icon: github
        href: https://github.com/jonnycomes
      - icon: linkedin
        href: https://linkedin.com/in/jcomes
format:
  html:
    theme: united
    css: styles.css
    include-after-body: |
      <script src="project-hover.js"></script>



